camunda.operate:
  elasticsearch:
    clusterName: sapptest-elastic
    host: elasticsearch
    port: 9200
    username: elastic
    password: changeme
  zeebe:
    brokerContactPoint: "zeebe:26500"
  zeebeElasticsearch:
    clusterName: sapptest-elastic
    host: elasticsearch
    port: 9200
    prefix: zeebe-record
    username: elastic
    password: changeme
